# Importing Library

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3]) # 1-D / vector

In [3]:
a

array([1, 2, 3])

In [4]:
type(a)

numpy.ndarray

In [5]:
a.shape

(3,)

In [6]:
a.ndim

1

In [8]:
b = np.array([[1,2,3],
             [4,5,6]])

In [9]:
type(b)

numpy.ndarray

In [10]:
b.shape

(2, 3)

In [11]:
b.ndim

2

In [19]:
c = np.array([[[1.0,2,3],
               [4,5,6],
               [7,8,9]]])

d = np.array([[[1,2,3],
               [4,5,6],
               [7,8,9]],
              
              [[10,11,12],
               [13,14,15],
               [16,17,18]]])

In [20]:
c

array([[[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]]])

In [21]:
d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [22]:
c.shape, d.shape

((1, 3, 3), (2, 3, 3))

In [23]:
a.dtype, d.dtype, c.dtype, d.dtype

(dtype('int32'), dtype('int32'), dtype('float64'), dtype('int32'))

In [25]:
a.size, b.size, c.size, d.size # dtermine how many elements are there in an array

(3, 6, 9, 18)

In [26]:
a.nbytes, b.nbytes, c.nbytes, d.nbytes

(12, 24, 72, 72)

In [27]:
a.data, b.data, c.data, d.data

(<memory at 0x000002173B8541C0>,
 <memory at 0x000002173B866D40>)

# Array Creation

In [28]:
array1 = np.array([1,2,3], dtype = 'int')

In [29]:
array1

array([1, 2, 3])

In [32]:
zeros = np.zeros((3,3), dtype = 'int')

In [33]:
zeros

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [34]:
ones = np.ones((3,3), dtype = 'int')

In [35]:
ones

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [37]:
full = np.full((2,3), 5)

In [38]:
full

array([[5, 5, 5],
       [5, 5, 5]])

In [41]:
identity = np.identity(3, dtype = 'int')

In [42]:
identity

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [49]:
eye = np.eye(3,3, -1)

In [50]:
eye

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [52]:
arange = np.arange(1,10,2)

In [53]:
arange

array([1, 3, 5, 7, 9])

In [64]:
linspace = np.linspace(1,100,50, dtype = 'int')

In [65]:
linspace

array([  1,   3,   5,   7,   9,  11,  13,  15,  17,  19,  21,  23,  25,
        27,  29,  31,  33,  35,  37,  39,  41,  43,  45,  47,  49,  51,
        53,  55,  57,  59,  61,  63,  65,  67,  69,  71,  73,  75,  77,
        79,  81,  83,  85,  87,  89,  91,  93,  95,  97, 100])

In [66]:
linspace.size

50

In [67]:
empty = np.empty((1,5))

In [68]:
empty

array([[2.12199579e-314, 4.67296746e-307, 4.56516657e-321,
        1.13526775e-311, 1.13576072e-311]])

In [70]:
for i in range(5):
    empty[:,i] = i
empty

array([[0., 1., 2., 3., 4.]])

# Array Indexing and slicing

# indexing

In [71]:
arr1 = np.array([1,2,3,4,5])

In [72]:
print(arr1)

[1 2 3 4 5]


In [73]:
arr1[0]

1

In [74]:
arr1[3]

4

In [75]:
arr1[-1]

5

In [76]:
arr2 = np.random.randint(1, 10, size = (3,3))

In [77]:
print(arr2)

[[5 4 9]
 [9 3 9]
 [5 5 2]]


In [78]:
arr2[0][0]

5

In [79]:
arr2[1][1]

3

In [80]:
arr2[1, 1]

3

In [81]:
arr3 = np.random.randint(1, 10, size = (2, 3, 3))

In [82]:
print(arr3)

[[[5 8 3]
  [1 6 8]
  [9 5 1]]

 [[7 3 8]
  [2 2 7]
  [6 7 2]]]


In [83]:
arr3[0][1][1]

6

In [84]:
arr3[0, 1, 1]

6

In [85]:
arr3[1,2,1]

7

# Slicing

In [86]:
print(arr1)

[1 2 3 4 5]


In [88]:
print(arr1[0: 3])

[1 2 3]


In [89]:
print(arr1[2:])

[3 4 5]


In [90]:
arr2

array([[5, 4, 9],
       [9, 3, 9],
       [5, 5, 2]])

In [92]:
arr2[0: 2, 0: 2]

array([[5, 4],
       [9, 3]])

In [94]:
arr2[1:, 1:]

array([[3, 9],
       [5, 2]])

# Manipilating array shapes
    
    1.reshape()
    2.resize()
    3.flatten()
    4.revel()
    5.defining array shape

# Reshape()

In [95]:
a = np.array([[1,2,3],
             [4,5,6]])

In [96]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [97]:
a.shape

(2, 3)

In [99]:
a_reshaped = np.reshape(a, (3, 2))

In [100]:
a_reshaped

array([[1, 2],
       [3, 4],
       [5, 6]])

In [101]:
a_reshaped.shape

(3, 2)

In [102]:
a.reshaped2 = np.reshape(a, (3, 3))

ValueError: cannot reshape array of size 6 into shape (3,3)

# Resize()

In [103]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [106]:
a_resized = np.resize(a, (4, 3))

In [107]:
a_resized

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [108]:
a_resized2 = np.resize(a, (3, 2))

In [109]:
a_resized2

array([[1, 2],
       [3, 4],
       [5, 6]])

# Ravel()

In [110]:
a = np.random.randint(1, 10, (2, 3)) # Return a view of the array

In [111]:
a

array([[8, 1, 4],
       [4, 7, 3]])

In [112]:
a_raveled = np.ravel(a)

In [113]:
a_raveled

array([8, 1, 4, 4, 7, 3])

In [114]:
a_raveled.shape

(6,)

In [120]:
a_raveled[0] = 0

In [122]:
a_raveled

array([0, 1, 4, 4, 7, 3])

In [123]:
a

array([[0, 1, 4],
       [4, 7, 3]])

Flatten()

In [124]:
a

array([[0, 1, 4],
       [4, 7, 3]])

In [125]:
a_flattened = a.flatten() # Return a copy of the array, always allocates a new memory.

In [126]:
a_flattened

array([0, 1, 4, 4, 7, 3])

In [127]:
a_flattened[0] = 100

In [128]:
a_flattened

array([100,   1,   4,   4,   7,   3])

In [129]:
a

array([[0, 1, 4],
       [4, 7, 3]])

deffining an array shape

In [130]:
a

array([[0, 1, 4],
       [4, 7, 3]])

In [132]:
a.shape = (3, 2)

In [133]:
a

array([[0, 1],
       [4, 4],
       [7, 3]])

In [134]:
a.shape = (5, 2)

ValueError: cannot reshape array of size 6 into shape (5,2)

Stacking

# Horizontal Stacking

In [135]:
a = np.arange(1, 10).reshape(3, 3)

In [136]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [137]:
b = 2*a

In [138]:
b

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [139]:
np.hstack((a, b))

array([[ 1,  2,  3,  2,  4,  6],
       [ 4,  5,  6,  8, 10, 12],
       [ 7,  8,  9, 14, 16, 18]])

In [140]:
np.column_stack((a, b))

array([[ 1,  2,  3,  2,  4,  6],
       [ 4,  5,  6,  8, 10, 12],
       [ 7,  8,  9, 14, 16, 18]])

In [141]:
np.concatenate((a, b), axis = 1)

array([[ 1,  2,  3,  2,  4,  6],
       [ 4,  5,  6,  8, 10, 12],
       [ 7,  8,  9, 14, 16, 18]])

# Vertical Stacking

In [142]:
np.vstack((a, b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [143]:
np.row_stack((a, b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [145]:
np.concatenate((a,b), axis = 0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

# Depth Stack

In [146]:
np.dstack((a, b))

array([[[ 1,  2],
        [ 2,  4],
        [ 3,  6]],

       [[ 4,  8],
        [ 5, 10],
        [ 6, 12]],

       [[ 7, 14],
        [ 8, 16],
        [ 9, 18]]])

# ProgramerDelowar.Designer